version: "3.1"
services:

  on-call-db:
    image: mariadb:latest
    hostname: on-call-db
    container_name: on-call-db
    environment:
      MYSQL_USER: on-call
      MYSQL_DATABASE: on-call
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 33060:3306
    volumes:
      - ./db-volume:/var/lib/mysql